#!/bin/bash
name="World";
address="https://www.seek.com.au/job/number?and_stuff";
title="Job Title";
mkdir sum;
cp shyam.pdf sum;
cp transcript.pdf sum;
cd sum;
../bash-sum.sh;
sum=$(sed '1,3d;s/ /\&nbsp;/g' < checksum.txt);
cd ..;
rm -r sum;
checksum="${sum//$'\n'/<br>}";
echo "<!DOCTYPE html><html><head><meta charset='utf-8'><title>Shyam Has Your Anomaly Mitigated!!! :D</title></head><body><font size=\"3\" color=\"#003366\" face=\"monospace,sans-serif\">🖖 Hello $name,<br><br>I am applying for <a href=\"$address\">$title</a>. I have attached my personal documentation for your reading (<font color=\"#666666\">p</font>)leisure; ten pages of pain-stakingly hand-crafted <span class=\"texhtml\" style=\"font-family: 'CMU Serif', cmr10, LMRoman10-Regular, 'Nimbus Roman No9 L', 'Times New Roman', Times, serif;\">L<span style=\"text-transform: uppercase; font-size: 70%; margin-left: -0.36em; vertical-align: 0.3em; line-height: 0; margin-right: -0.15em;\">a</span>T<span style=\"text-transform: uppercase; margin-left: -0.1667em; vertical-align: -0.5ex; line-height: 0; margin-right: -0.125em;\">e</span>X</span>, dot, ETC…<br><br>I've read <a href=\"http://steve-yegge.blogspot.com.au/2006/03/truth-about-interviewing.html\">The Truth About Interviewing</a>; I am confident I would fail every single query Steve typed...but I like to think of myself as an <font color=\"#336600\">upward curve</font>!?!<br><b>In any case:</b><br>&nbsp;<font color=\"#990000\">‣</font> I would consult <a href=\"https://www.google.com.au/\">Google</a>; because it contains the knowledge of the masses.<br>&nbsp;<font color=\"#990000\">‣</font> I would <a href=\"http://www.commitstrip.com/en/2016/12/21/google-search-master/\">ask</a> for well-documented syntactic/semantic/ETC advice.<br><b>Thoughts:</b><br>&nbsp;<font color=\"#990000\">‣</font> I am a <a href=\"http://www.hanselman.com/blog/AmIReallyADeveloperOrJustAGoodGoogler.aspx\">Good Googler</a>!<br>&nbsp;<font color=\"#990000\">‣</font> I am a <a href=\"http://catb.org/esr/writings/unix-koans/recruiter.html\">UNIX Hacker</a>!<br><br><i>I am a functional hacker. I am a <a href=\"https://rosettacode.org/wiki/User:Shyam_Has_Your_Anomaly_Mitigated/cons\">con-man</a>. I do not sign NDAs. I wear a <a href=\"https://blog.plover.com/prog/burritos.html\">sombrero</a> to job interviews. Employ me.</i><br><br>I'm <a href=\"https://xkcd.com/927/\">planning</a> to become a formally verified <a href=\"https://en.wikipedia.org/wiki/List_of_programming_language_researchers\">linguist/grammarian/lexicographer/ETC</a> (<font color=\"#666666\">metaprogrammer</font>); <a href=\"https://youtu.be/kJa2kwoZ2a4\">WUBBA LUBBA DUB DUB</a>!!! :D<br><br><font color=\"#000000\"><font size=\"4\"><font color=\"#CCCCCC\">LIVE LONG AND PROSPER \V/,</font><br><font color=\"#999999\">AGENT S.</font><br><font size=\"6\">🕴</font><br><font color=\"#F4F4F4\"><font color=\"#CCCCCC\">M</font>igrating<font color=\"#CCCCCC\"> I</font>nfestive<font color=\"#CCCCCC\"> B</font>ugs</font> <u>!</u><font color=\"#FFFFFF\"><u>!</u></font></font></font></font><br><br><br><tt><b>checksum.txt</b><br>Total&nbsp;Algorithms&nbsp;Used:&nbsp;15<br><br>./shyam.pdf<br>$checksum</tt></body></html>" > email.htm;
